name: Lint check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: copy .env.example to .env
        run: cp .env.example .env
      - name: Run ESLint check
        run: npm run lint