name: Prettier check

on: [push]

jobs:
  lint:
    name: Lint with Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: npm install

      - name: Run ESLint check
        run: npm run lint
